# Generated by Django 3.0.3 on 2020-02-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubsreview30866', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='publication',
            new_name='Publication',
        ),
    ]
