# Generated by Django 3.0.3 on 2020-02-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubsreview30866', '0002_auto_20200226_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Publication',
            new_name='publication_name',
        ),
    ]
