# Generated by Django 3.0.3 on 2020-02-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubsreview30866', '0003_auto_20200227_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='publication_name',
            new_name='publicationName',
        ),
    ]
