# Generated by Django 3.0.3 on 2020-02-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubsreview30866', '0004_auto_20200227_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='publicationName',
            new_name='pub',
        ),
    ]
