# Generated by Django 3.0.3 on 2020-02-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel30882', '0001_initial'),
        ('pubsreview30866', '0005_auto_20200227_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel30882.Publication'),
        ),
    ]
