# Generated by Django 3.0.3 on 2020-02-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicationview30890', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='PublicationCategory',
        ),
    ]
