# Generated by Django 3.0.3 on 2020-02-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciencepublications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publicationEissn',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publicationIssn',
            field=models.CharField(max_length=8),
        ),
    ]
