# Generated by Django 3.0.3 on 2020-02-24 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciencepublications', '0002_auto_20200223_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
