# Generated by Django 3.0.3 on 2020-02-28 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sciencepublications', '0003_delete_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('catind', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('issn', models.CharField(max_length=9)),
                ('eissn', models.CharField(max_length=9)),
                ('name2', models.CharField(max_length=256)),
                ('issn2', models.CharField(max_length=9)),
                ('eissn2', models.CharField(max_length=9)),
                ('points', models.IntegerField()),
                ('categories', models.ManyToManyField(blank=True, to='sciencepublications.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Simple',
        ),
    ]
